apiVersion: v1
kind: Secret
metadata:
  name: chat-db-secret
  namespace: reels-chat
type: Opaque
stringData:
  POSTGRES_PASSWORD: "NHcl79KM2A2UQVJN"
  DATABASE_URL: "postgresql://chatuser:NHcl79KM2A2UQVJN@postgres-svc:5432/chatdb"