apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  namespace: reels-chat
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: reels-chat
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        # Thay thế image này bằng ECR repo của bạn trong pipeline
        image: node:16-alpine 
        ports:
        - containerPort: 3001
        envFrom:
          - configMapRef:
              name: reels-chat-config
