apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  namespace: reels-chat
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: reels-chat
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: 476114143297.dkr.ecr.ap-southeast-1.amazonaws.com/reels-chat/backend:latest 
        ports:
        - containerPort: 3001
        env:
          - name: PORT
            value: "3001"
          - name: ALLOWED_ORIGIN
            valueFrom:
              configMapKeyRef:
                name: reels-chat-config
                key: REACT_APP_BACKEND_URL
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: chat-db-secret
                key: DATABASE_URL
          readinessProbe:
            httpGet:
              path: /health
              port: 3001
            initialDelaySeconds: 3
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 3001
            initialDelaySeconds: 10
            periodSeconds: 20
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
